Algoritmo "semnome"

//3.2// Crie um algoritmo que calcule a área de um triângulo,
//considerando a fórmula “AREA = (base * altura)/2”. Utilize as variáveis
//AREA,
// BASE e ALTURA e os operadores aritméticos necessários.
 Var
 area,base,altura:real
 
 

Inicio
 escreva("Qual o valor da base")
 leia(base)
 escreva("Qual o valor da altura")
 leia(altura)

 area<-(base*altura)/2
 
 escreva("A area do triangulo é: " ,area)


Fimalgoritmo