Algoritmo "semnome"
// 3.3// Faça um algoritmo que: a) Leia o nome; b) Leia o sobrenome;
 //c) Concatene o nome com o sobrenome; d) Apresente o nome completo.
Var
   primeiroNome,sobreNome:caracter


Inicio
escreva("Qual o seu primeiro nome: ")
leia(primeiroNome)
escreva("Qual o seu sobrenome: ")
leia(sobreNome)

escreva(" O nome completo do aluno é: " ,primeiroNome , " " ,sobreNome)

Fimalgoritmo