Algoritmo "semnome"
//cafe_per_capita = (cafe+extra)/alunos
Var
cafe_percapita,cafe,alunos,extra: real


Inicio
escreva("Quanto de cafe temos nós:")
leia(cafe)

escreva("quantos alunos temos em sala; ")
leia(alunos)

escreva("Quanto de café extra teremos? ")
leia(extra)

cafe_percapita<- (cafe+extra)/alunos

escreva("Os alunos vão ter a disposição" ,cafe_percapita , " litros")

Fimalgoritmo