Algoritmo "soma"

Var
a,b,soma,subtracao, multiplicacao: inteiro
divisao: real

Inicio
escreva("Digite um númer:")
leia(a)

escreva("Digite outro número:")
leia(b)

soma <- a+ b
subtracao <- a-b
multiplicacao <- a*b
divisao <- a/b

escreval("A soma dos números é : " ,soma  )
escreval("A subtração dos números é : " ,subtracao)
escreval("A mutiplicação dos números é : " ,multiplicacao )
escreval("A divisão dos números é : ", divisao)

Fimalgoritmo